### ISSUE TITLE
Fix Rondell

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Embedded-Controller#29]
## Description

Rondell can't be calibrated.

## ToDo

- [x] Check if the problem is *hardware* or *software* dependent
- [x] Fix the Error

**Comment by HuangQing23** [comment]
function 'setExtrema' was called in 'createRondell' after 'setUpRondell(address)' to set the max/min_ldr_value during the rondell is rotating.
I add some PRINT_DEBUGs to test the value of adc_read( ) and the max/min_ldr_value and the MEAN_OF_LDR_VALUES which is half of (min_ldr_value+max_ldr_value), here is the code:
  static void setExtrema(void) {
    PRINT_DEBUG("ENTERED setExtrema")
    moveRondellClockwise();
    uint16_t dataCollectionTime_ms = 15000;
    uint16_t counter = 0;
    while (counter <= dataCollectionTime_ms) {
        uint16_t current_val = adc_read();
        PRINT_DEBUG("%u",current_val)
        if (current_val > rondell.max_ldr_value) {
            PRINT_DEBUG("bigger:%u",current_val)
            rondell.max_ldr_value = current_val;
        }
        if (current_val < rondell.min_ldr_value) {
            PRINT_DEBUG("smaller:%u",current_val)
            rondell.min_ldr_value = current_val;
        }
        counter += 10;
        sleep_ms(10);
    }
...
}
And we can see the screenshot:
![d5dc2a9696aa18a51de0192d404509b](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/assets/148549041/66ece6d3-2869-4edd-8c9c-4aa9de66f80a)
so we can see that we just execute once  
if (current_val > rondell.max_ldr_value) {
            PRINT_DEBUG("bigger:%u",current_val)
            rondell.max_ldr_value = current_val;
        }
because we initiate rondell.max_ldr_value as 0, so it make sense.

But it seems like the value adc_read( ) return will eternally be 4095 and it's equal to the max/min_ldr_value and the MEAN_OF_LDR_VALUES.

That means, the processing will be stuck at funtion 'findLongHole':
static void findLongHole(bool *longHoleFound) {
    PRINT_DEBUG("entered FINDLONGHOLE")
    int high_counter = 0;
    passDarkPeriod(0);
    PRINT_DEBUG("1")
    PRINT_DEBUG("%d",rondell.max_ldr_value)
    PRINT_DEBUG("%d",rondell.min_ldr_value)
    PRINT_DEBUG("%d",MEAN_OF_LDR_VALUES)
    PRINT_DEBUG("%u",adc_read())
    while (adc_read() < MEAN_OF_LDR_VALUES) {
        PRINT_DEBUG("2")
        if (high_counter >= 500) {
            break;
        }
        PRINT_DEBUG("3")
        high_counter += 10;
        sleep_ms(10);
    }
    PRINT_DEBUG("4")
    if (high_counter >= 500) {
        *longHoleFound = true;
        return;
    }
}
![a26d43e90251c5feaf90ee20afccd7e](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/assets/148549041/c990d001-84d7-40a0-a918-8467c7f7dc1f)

So maybe the problem is in function 'adc_read( )'

**Comment by HuangQing23** [comment]
Found that the pin we use is wrong. With the new PCB board and connection we shall use 27 instead of 28. So we check it and the rondell can work.

**Comment by HuangQing23** [comment]
And a new problem is the rondell cannot reach/recognize the postion 2 and 0, it can only recognize the position 1 and 3.
@DavidFederl tried to let the rondell rotating at 50000, and it did work. So we can know that the speed we use for motor up/down is too fast for rondell. 
So we shall fix the conflict issues of the definition of speed between motor and rondell, let rondell run at lower speed 50000.
