### ISSUE TITLE
Measuring the torque as fast as possible

### ISSUE THREAD

**Issue by kamilloo1** [ES-EDU-SIEGMA/Embedded-Controller#41]
Currently, the torque is measured every 100 ms because a delay is programmed in the code.

For better accuracy of measurements, the torque could be measured every full step.

**Comment by YULEMING** [comment]
# TMC Library issue
In our c version tmc library, I didn't find the configuration of register 0x03:
```c
  const static uint8_t ADDRESS_REPLYDELAY = 0x03;
  union ReplyDelay
  {
    struct
    {
      uint32_t reserved_0 : 8;
      uint32_t replydelay : 4;
      uint32_t reserved_1 : 20;
    };
    uint32_t bytes;
  };
```
which does have in the cpp version:
https://github.com/peterpolidoro/TMC2209/blob/main/src/TMC2209.h#L338

This can be used as SENDDELAY for read access (time until reply is sent). I mean, replace the `sleep` stuff in `TMC2209_read(...)` which doesn't have in the cpp version.

See [TMC2209_datasheet_rev1.09.pdf](https://github.com/ES-EDU-SIEGMA/Documentation/blob/main/datasheets/TMC2209_datasheet_rev1.09.pdf) 4.1.2 Read Access. Page 19th and 24th. Search `SENDDELAY`.

Did they remove this after testing? Or have they never used this?

**Comment by YULEMING** [comment]
I commented out post_read_delay_repeat and tested the code:
[2023.11.14-delay test 2-115200.log](https://github.com/ES-EDU-SIEGMA/Documentation/blob/main/documentation/TorqueData/2023.11.14-delay%20test%202-115200.log)
This post_read_delay_repeat is above 4. This actually will cause the code sleep_us(40). After this sleep, code will sleep 10ms again. I removed this 40us and it works well. So we are not so time critical with 10ms+40us.

**Comment by YULEMING** [comment]
I also looked at the commit history and I found that at the very beginning version of tmc library, there were only post_read_delay_repeat, see [TMC2209.c](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/commit/1d97fb55d524355890d47266c91df3e118120bbc#diff-536b14b76716f29498fc904872aa6730b7453d460d2585df3454edf92e54c295) line 840. Then they added sleep_ms(10), see [here](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/commit/fbed7ed5ad3f124c0892825ca2875757b27b2021#diff-51a71590ec8e73723786f6959217f9331ae600a7747f48bef4eb80b8ffa8a1bb) line 768.
So I think 10ms is not tested, they just used 10ms because it's definitely enough.

**Comment by YULEMING** [comment]
```c
for loop 1 {
	dispenser1_upState:20ms; // get torque at the end of 20ms
	dispenser2_upState:20ms; // get torque at the end of 40ms
	dispenser3_upState:20ms; // get torque at the end of 60ms
	dispenser4_upState:20ms; // get torque at the end of 80ms
}
for loop 2 {
	dispenser1_upState:20ms; // get torque at the end of 100ms
	dispenser2_upState:20ms; // get torque at the end of 120ms
	dispenser3_upState:20ms; // get torque at the end of 140ms
	dispenser4_upState:20ms; // get torque at the end of 160ms
}
...
```
I think this is what happened. Only one `dispenserDoStep` can run at the same time(I hope I'm right?). Others need to wait until the former one is finished.
The torque's value is updated every full step from motor to TMC SGRESULT register. We have 4 motors and 4 TMC. We're sure that this update is happening in parallel. But the process that gets this value from TMC to TINY, because we only have 1 TINY connected to 4 TMC through UART divided into 4, we can't do it in parallel but one by one.

**Comment by YULEMING** [comment]
Let's say all 4 dispensers are active.
In your case, we skipped 3 motorIsCommunicating. If we can skip motorIsCommunicating before getting into upState function and other State functions, then I think we can skip all. **We can test it.**
For example:
```c
void processMessage(...) {
    process command;
    for all active dispensers: check motor  // Or we don't check at all
    do {
        for all active dispensers: run State function
    } while (not all dispensers are sleeping)
}
```
If that's true, 1 dispenser reads 1 torque or 4 torque, there would be no difference in terms of time. It depends on how we implement the code in the new architecture.
We can use your code like this:
```c
void open(all active dispensers) {
    for each dispenser: read torque;
    for each dispenser: evaluate top state;
    ...
    for each dispenser: do something;
    ...
}
```
Anyway, it depends on the new architecture. We can discuss what behaviors we expect the object dispenser to have.

**Comment by YULEMING** [comment]
I should be more precise,
```c
dispenser1:
  check motor1
  read torque1
dispenser2:
  check motor2
  read torque2
dispenser3:
  check motor3
  read torque3
dispenser4:
  check motor4
  read torque4
```
Your code is,
```c
dispenser1:
  check motor1
  read torque1
  read torque2  // These 3 torques are read without checking motor 2,3,4, not following checking their own
  read torque3  // motors closely. In the former version, every torque reading follows its own
  read torque4  // motor checking. Here skipped motorIsCommunicating 2,3,4 for once.
dispenser2:
  check motor2
  read torque1
  read torque2
  read torque3
  read torque4
dispenser3:
  check motor3
  read torque1
  read torque2
  read torque3
  read torque4
dispenser4:
  check motor4
  read torque1
  read torque2
  read torque3
  read torque4
```

**Comment by YULEMING** [comment]
After testing, SENDDELAY = 2, and sleep_ms(1) works well.
We can sleep less time, but 1ms is enough and stable.
