### ISSUE TITLE
New implementation of time to hold top position.

### ISSUE THREAD

**Issue by kamilloo1** [ES-EDU-SIEGMA/Embedded-Controller#55]
Because we made measuring torque faster in [this ](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/issues/41) issue, the time to hold the top position needs to be recalculated and implemented.

**Comment by YULEMING** [comment]
The current `dispenser` has an attribute `haltSteps`. It is used in topState to control the time that the dispenser stops at the top position. Because we are going to use time instead of steps, I recommend that we change `haltSteps` to `haltTime`, which means: *This dispenser is going to stop at the top position for 'haltTime' ms*. But this will influence some other dispenser functions. Details are as follows:
### File: [dispenser.h](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/blob/main/src/dispenser/dispenser.h#L36)
```c
struct dispenser {
    ...
    // uint16_t haltSteps;
    uint32_t haltTime;
    ...
};
```
### File: [dispenser.c](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/blob/main/src/dispenser/dispenser.c)
```c
void dispenserSetHaltTime(dispenser_t *dispenser, uint32_t haltTime) {
//    dispenser->haltSteps = haltTime / DISPENSER_STEP_TIME_MS;
    // Change dispenser->haltSteps to dispenser->haltTime
    dispenser->haltTime = haltTime;
    // PRINT_DEBUG("Dispenser %u will stop after %hu steps", dispenser->address, dispenser->haltSteps)
}
```
```c
void dispenserCreate(dispenser_t *dispenser, SerialAddress_t address, serialUart_t uart,
                     uint8_t dispenserCL, uint16_t searchTimeout) {
    ...
    // dispenser->haltSteps = 0;
    dispenser->haltTime = 0;
    ...
}
```
```c
void dispenserEmergencyStop(dispenser_t *dispenser) {
    ...
    // dispenser->haltSteps = 0;
    dispenserSetHaltTime(dispenser, 0);
    ...
}
```
* `haltTime` would be assigned every time when it needs to work, but it would be stable if we set it to 0. E.g. what if we say: *Let all dispensers start to work as long as its `haltTime` is not 0?* But that dispenser stopped last time without setting `haltTime` to 0?
```c
static dispenserState_t errorState(dispenser_t *dispenser) {
    ...
    if (...)) {
        ...
        // dispenser->haltSteps = 0;
        dispenserSetHaltTime(dispenser, 0);
        ...
    }
    ...
}
```
```c
static dispenserState_t sleepState(dispenser_t *dispenser) {
//    if (dispenser->haltSteps > 0) {
//        enableMotorByPin(&dispenser->motor);
//        moveMotorUp(&dispenser->motor);
//        return upState_t;
//    }
    return sleepState_t;
}
```
* This `sleepState` will check whether the dispenser really finished or not by checking `haltSteps`. Because we use `haltTime` instead of `haltSteps`, I don't see any situation once we get into `sleepState` but the dispenser still has unfinished steps and needs to go back to `upState`. No need to do it anymore.
```c
static dispenserState_t topState(dispenser_t *dispenser) {
    PRINT_DEBUG("topState")
    // Change dispenser->haltSteps to dispenser->haltTime
    sleep_ms(dispenser->haltTime);
    dispenserSetHaltTime(dispenser, 0);
    return downState_t;
}
```
```c
static dispenserState_t downState(dispenser_t *dispenser) {
    ...
    if (...)) {
        ...
        // dispenser->haltSteps = 0;
        dispenserSetHaltTime(dispenser, 0);
        ...
    }
    ...
}
```

**Comment by YULEMING** [comment]
The current `dispenser` also has attributes `stepsUp` and `stepsDown`. Because of the above changes, these two are only working as counters. We don't do any `if condition` stuff on them. We can also get rid of them.
### File: dispenser.h
```c
struct dispenser {
    ...
    // uint16_t stepsDone;
    // uint16_t stepsUp;
    // This haltSteps is used in topState, we can change it to "haltTime"
    // uint16_t haltSteps;
    uint32_t haltTime;
    ...
};
```
### File: dispenser.c
```c
void dispenserCreate(dispenser_t *dispenser, SerialAddress_t address, serialUart_t uart,
                     uint8_t dispenserCL, uint16_t searchTimeout) {
    ...
    // This haltSteps is used in topState, we can change it to "haltTime"
    // dispenser->haltSteps = 0;
    dispenser->haltTime = 0;
    // dispenser->stepsDone = 0;
    ...
}
```
```c
static dispenserState_t upState(dispenser_t *dispenser) {
    ...
    // If the torque is below 10 twice in a row, stop
    if (torque < 10){
        ...
        if (counterTorque == 2){
            ...
            // dispenser->stepsUp = dispenser->stepsDone;
            ...
        }
    }
    else ...

    if (!limitSwitchIsClosed(dispenser->limitSwitch)) {
        // dispenser->stepsDone++;
    }
    ...
}
```
```c
static dispenserState_t downState(dispenser_t *dispenser) {
    ...
    if (limitSwitchIsClosed(dispenser->limitSwitch)) {
        ...
        // dispenser->haltSteps = 0;
        dispenserSetHaltTime(dispenser, 0);
        ...
    }
    // dispenser->stepsDone++;
    ...
}
```

**Comment by glencoe** [comment]
Seems reasonable. Please open a pull request that features your changes

**Comment by YULEMING** [comment]
Some problems are found with the above method, and this should be continued based on the newly refactored code.

**Comment by YULEMING** [comment]
Based on `develop` branch.
```c
static dispenserState_t topState(dispenser_t *dispenser) {
    PRINT_DEBUG("topState")
    if (dispenser->haltTime > 0) {
        sleep_ms(TOP_TIME_SLOT);
        dispenser->haltTime = dispenser->haltTime - TOP_TIME_SLOT;
        return topState_t;
    }
    // reset to 0 when change to down state.
    dispenserSetHaltTime(dispenser, 0);
    moveMotorDown(&dispenser->motor);
    return downState_t;
}
```
The `TOP_TIME_SLOT` is defined as 1. Assume command `100;\n` is sent. Dispenser will sleep 1ms at the top position 100 times. If dispenser sleeps 100ms at the top position 1 time, others will have to wait 100ms.
```c
static dispenserState_t sleepState(dispenser_t *dispenser) {
    if (dispenser->haltTime > 0) {
        enableMotorByPin(&dispenser->motor);
        moveMotorUp(&dispenser->motor);
        return upState_t;
    }
    return sleepState_t;
}
```
`sleepState` will check `haltTime` instead of `haltSteps`.

#### When the refactoring is finished, I will implement the changes in new code.

**Comment by YULEMING** [comment]
Make sense. Thank you for telling me that.
1. When I was doing the task: measure the torque more frequently, there was a situation that when all 4 dispensers are working, when no sleep in the end of `TMC2209_read`, 2 of 4 dispensers won't stop correctly. They stuck in the `upState`. But it worked well when 1 dispenser is working. According to how you sovled your #56, I think the reason is:
```c
static uint8_t counterTorque = 0;
static uint16_t torque = 0;
...
static dispenserState_t upState(dispenser_t *dispenser) {
    torque = motorGetTorque(dispenser->address);
    PRINT_DEBUG("upState")
    PRINT_DEBUG("Torque: %i", torque)

    // If the torque is below 10 twice in a row, stop
    if (torque < 10){
        counterTorque++;
        if (counterTorque == 2){
            PRINT_DEBUG("detect Top Position")
            stopMotor(dispenser->address);
            counterTorque = 0;
            return topState_t;
        }
    }
    else counterTorque = 0;
    return upState_t;
}
```
the `torque` here is a shared variable because we are using if statement. So the last counted torque is from another dispenser. I will try to make `torque` be non-shared and try to remove the `sleep` in the end of `TMC2209_read` to **reduce the cycle time**. Even if it has no influence on the cycle time, I still don't think it's a good idea to make `torque` here be shared.

2. I will measure the cycle time, figure out the relation between the input and real time, and adjust the sleep time in `topState`

**Comment by YULEMING** [comment]
In the old `topState`, no sleep, only count halt steps. It's like: 1000 / 100 = 10 halt steps in total. Then just run `topState` 10 times. When I do `sleep` stuff, I have to consider other dispensers. Because 1 dispenser sleeps, it has to wait others to sleep. I think that's why there is a `othersTriggered` in the old `topState`. I think we do need an attribute to let the current dispenser know how many dispensers are working at the same time, and to reduce correct time or steps in one `topState`.

**Comment by YULEMING** [comment]
Before one dispenser really runs one of the `xxxState` functions, it will still check the motor, which already spent 1ms. Same on topState. I saw the new downState function, there will be 1 or 2 times `motorGetTorque`. Tomorrow I will try to reduce the 1ms sleep at first. If we can't, here is my new thought:
1. use a shared counter variable declared in dispenser.h, so that it can be reset in the controller file and can be accessed in the dispenser.c file
2. reset in the beginning of every `do while` loop in controller file
3. after each `motorGetTorque`, counter++, so that we know how many 1ms already spent, in order to reduce the halt counter in `topState`.

**Comment by YULEMING** [comment]
Find the proper method to implement the timing for topstate. #76 
After fixing #84

**Comment by YULEMING** [comment]
#### Important changes:
* @HuangQing23 moved motor check out of and before the do-while loop
* Running sequence in topState changed from:
    * motor check 
    * dispenser run
    * motor check 
    * dispenser run
    * motor check 
    * dispenser run
    * motor check 
    * dispenser run
* To: (motor check is done before going into this running sequence)
    * dispenser run
    * dispenser run
    * dispenser run
    * dispenser run
#### Based on the above changes
* The countdown method (without sleep): countdown by the number of dispensers now in topState from 1000 (number from the command) to 0,
    * approximate to 1000ms
    * the longer the halt time, the more significant the deviation
But in my point of view, the longest halt time should be the time that the dispenser need from full to empty. Longer halt time makes no or less sense.

**Comment by YULEMING** [comment]
### Attention
* Please note that the same code spends different times in the `debug` and `release` modes because the `PRINT_DEBUG` stuff won't be counted in `release` mode.
* If the halt time is longer than the command, and there is `PRINT_DEBUG` or something like that, remove or comment relevant statement.
